definitions:
  steps:
    - step: &build-app
        name: "Build application"
        image: maven:3.8.2-jdk-11
        caches:
          - maven
        script:
          - mvn clean install
        artifacts:
          - target/**
    - step: &deploy-app
        name: Deploy Application to AWS S3
        script:
          - pipe: atlassian/aws-s3-deploy:1.1.0
            variables:
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
              S3_BUCKET: $S3_BUCKET
              LOCAL_PATH: "target"


pipelines:
  default:
    - step:
        name: "Run unit tests"
        image: maven:3.8.2-jdk-11
        caches:
          - maven
        script:
          - mvn test
  custom:
    Deploy to Live:
      - step:
          *build-app
      - step:
          <<: *deploy-app
          deployment: live
    Deplot to Stage:
      - step:
          *build-app
      - step:
          <<: *deploy-app
          deployment: stage
