image: maven:3.8.2-jdk-11

definitions:
  steps:
    - step: &build-s3-app
        name: "Build application"
        caches:
          - maven
        script:
          - mvn clean install -DskipTests
        artifacts:
          - target/spring-boot-pipeline-demo.jar
    - step: &deploy-s3-app
        name: Deploy Application to AWS S3
        script:
          - pipe: atlassian/aws-s3-deploy:1.1.0
            variables:
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
              S3_BUCKET: $S3_BUCKET
              ACL: 'public-read'
              LOCAL_PATH: "target"


pipelines:
  default:
    - step:
        name: "Run unit tests"
        caches:
          - maven
        script:
          - mvn test
  custom:
    Deploy to Live:
      - step: 
          *build-s3-app
      - step:
          <<: *deploy-s3-app
          deployment: live
    Deploy to Stage:
      - step: 
          *build-s3-app
      - step:
          <<: *deploy-s3-app
          deployment: stage
